language: node_js
node_js:
  - "8"
  - node

script: echo "Running tests against $(node -v)..."

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage --coverageReporters=text-lcov | coveralls
